In [11]:
import pandas as pd
import savReaderWriter as spss
import numpy as np
import researchpy as rp
import statsmodels.api as sm
from statsmodels.formula.api import ols
import matplotlib.pyplot as plt
import scipy.stats as stats
from statsmodels.multivariate.manova import MANOVA
from scipy.stats import trim_mean, kurtosis
from scipy.stats.mstats import mode, gmean, hmean
 	
import os

In [12]:
print("The working directory was " , os.getcwd()) #Where was it set?
os.chdir("/Dataset") #Changes the working directory
print("The working directory was " , os.getcwd()) #Validate where it was set

The working directory was  c:\Users\PC\Dropbox\Python\Python for Data Analysis\Suicide\Dataset
The working directory was  c:\Users\PC\Dropbox\Python\Python for Data Analysis\Suicide\Dataset

In [23]:
data = pd.DataFrame(list(spss.SavReader('Youth suicide data 2010 to 2015.sav')))
with spss.SavReaderNp ("Youth suicide data 2010 to 2015.sav") as reader:
    records = reader.all()
df = pd.DataFrame(records, errors = 'coerce')
df2 = pd.to_datetime(InjuryDate, errors = 'coerce')
df2 = pd.to_datetime(DeathDate, errors = 'coerce')
df2 = pd.to_datetime(DeathPronouncedDate, errors = 'coerce')
df2 = pd.to_datetime(SpecimensDate, errors = 'coerce')
df2 = pd.to_datetime(InjuryDate_myr, errors = 'coerce')
df2 = pd.to_datetime(DeathDate_myr, errors = 'coerce')
df2 = pd.to_datetime(DeathPronouncedDate_myr, errors = 'coerce')
df2 = pd.to_datetime(SpecimensDate_myr, errors = 'coerce')
df2.head()

In [76]:
maov = MANOVA.from_formula('ORF3 + VOC3 + MCC3 ~ sped', data=df)

In [102]:
df.describe()

,sid,Gender,ethnic,sped,poverty,proficiency,ORF1,ORF2,ORF3,VOC1,VOC3,MCC1,MCC2,MCC3,Rit_Tot
count,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.00000,250.000000,250.000000,250.000000,250.000000,250.00000
mean,125.500000,0.496094,4.519531,0.235962,0.507812,2.096000,143.416000,150.091995,164.979996,18.31200,20.228001,13.916000,14.412000,15.892000,224.38400
std,72.312973,0.500977,1.448242,0.425537,0.500977,0.681647,40.436417,40.291245,37.883717,4.78689,4.112868,3.404011,2.937477,3.078677,9.90743
min,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,31.000000,38.000000,56.000000,4.00000,7.000000,4.000000,4.000000,5.000000,198.00000
25%,63.250000,0.000000,4.000000,0.000000,0.000000,2.000000,116.000000,121.250000,140.250000,15.00000,18.000000,12.000000,13.000000,15.000000,219.00000
50%,125.500000,0.000000,5.000000,0.000000,1.000000,2.000000,145.000000,148.000000,168.000000,19.50000,22.000000,15.000000,15.000000,16.500000,224.00000
75%,187.750000,1.000000,5.000000,0.000000,1.000000,3.000000,172.000000,177.750000,191.000000,22.00000,23.000000,17.000000,16.000000,18.000000,231.00000
max,250.000000,1.000000,7.000000,1.000000,1.000000,3.000000,252.000000,267.000000,253.000000,25.00000,25.000000,20.000000,20.000000,20.000000,253.00000

In [78]:
print(maov.mv_test())

Multivariate linear model
================================================================

----------------------------------------------------------------
       Intercept         Value  Num DF  Den DF   F Value  Pr > F
----------------------------------------------------------------
          Wilks' lambda  0.0260 3.0000 246.0000 3075.7577 0.0000
         Pillai's trace  0.9740 3.0000 246.0000 3075.7577 0.0000
 Hotelling-Lawley trace 37.5092 3.0000 246.0000 3075.7577 0.0000
    Roy's greatest root 37.5092 3.0000 246.0000 3075.7577 0.0000
----------------------------------------------------------------

----------------------------------------------------------------
             sped          Value  Num DF  Den DF  F Value Pr > F
----------------------------------------------------------------
             Wilks' lambda 0.7160 3.0000 246.0000 32.5321 0.0000
            Pillai's trace 0.2840 3.0000 246.0000 32.5321 0.0000
    Hotelling-Lawley trace 0.3967 3.0000 246.0000 32.5321 0.0000
       Roy's greatest root 0.3967 3.0000 246.0000 32.5321 0.0000
================================================================

In [120]:
s1 = stats.shapiro(df.ORF3.dropna())
s2 = stats.shapiro(df.VOC3.dropna())
s3 = stats.shapiro(df.MCC3.dropna())
s4 = stats.shapiro(df.sped.dropna())

DV = df.sped.dropna()

l1 = stats.levene(df.ORF3.dropna(), DV)
l2 = stats.levene(df.VOC3.dropna(), DV)
l3 = stats.levene(df.MCC3.dropna(), DV)

print('-------------------')
print('Oral Reading Spring = {}'.format(s1))
print('Vocabulary Spring = {}'.format(s2))
print('Reading Comprehension Spring = {}'.format(s3))
print('-------------------')
print('Oral Reading Spring= {}'.format(l1))
print('Vocabulary Spring= {}'.format(l2))
print('Reading Comprehension Spring= {}'.format(l3)) 
print('-------------------')

-------------------
Oral Reading Spring = (0.9881916642189026, 0.03821108862757683)
Vocabulary Spring = (0.8874883651733398, 1.1367143120874501e-12)
Reading Comprehension Spring = (0.9087740182876587, 3.317933428004238e-11)
-------------------
Oral Reading Spring= LeveneResult(statistic=389.42007909388974, pvalue=1.806266732392293e-64)
Vocabulary Spring= LeveneResult(statistic=199.52450106268373, pvalue=2.4352658020896093e-38)
Reading Comprehension Spring= LeveneResult(statistic=252.08034103980927, pvalue=3.136611450932214e-46)
-------------------

In [114]:
def box_m(ORF1,VOC1,MCC1,Gender):

        global Xp

        m = 2
        k = len(np.cov(X0))
        n_1 = len(X0[0])
        n_2 = len(X1[0])
        n = len(X0[0])+len(X1[0])

        Xp = ( ((n_1-1)*np.cov(X0)) + ((n_2-1)*np.cov(X1)) ) / (n-m)

        M = ((n-m)*np.log(np.linalg.det(Xp))) \
         - (n_1-1)*(np.log(np.linalg.det(np.cov(X0)))) - (n_2-1)*(np.log(np.linalg.det(np.cov(X1))))

        c = ( ( 2*(k**2) + (3*k) - 1 ) / ( (6*(k+1)*(m-1)) ) ) \
            * ( (1/(n_1-1)) + (1/(n_2-1)) - (1/(n-m)) )

        df = (k*(k+1)*(m-1))/2

        c2 = ( ((k-1)*(k+2)) / (6*(m-1)) ) \
            * ( (1/((n_1-1)**2)) + (1/((n_2-1)**2)) - (1/((n-m)**2)) )

        df2 = (df+2) / (np.abs(c2-c**2))

        if (c2>c**2):

            a_plus = df / (1-c-(df/df2))

            F = M / a_plus

        else:

            a_minus = df2 / (1-c+(2/df2))

            F = (df2*M) / (df*(a_minus-M))

        print('M = {}'.format(M))
        print('c = {}'.format(c))
        print('c2 = {}'.format(c2))
        print('-------------------')
        print('df = {}'.format(df))
        print('df2 = {}'.format(df2))
        print('-------------------')
        print('F = {}'.format(F))